### PR TITLE
Upload rare events supplementary figure

### PR DESCRIPTION
**Pull request by yardencsGitHub**
Addressing part of reviewer comment 1.4

### CODE REVIEW

**Comment by NickleDave** [comment]
I guess this figure is made with the notebook in #123 and I can merge it in as well?

**Comment by yardencsGitHub** [comment]
Figure panels are made in the notebook.
I made another commit after completing the analysis of the hidden_size=64 data.
The notebook's output was converted to vector images and moved to illustrator (hence the .ai)

**Comment by NickleDave** [comment]
ok, so does that mean I should merge them in or no? 🙂

**Comment by yardencsGitHub** [comment]
Yes please

**Comment by yardencsGitHub** [comment]
And also sync with overleaf please

**Comment by NickleDave** [comment]
@yardencsGitHub Overleaf is synced

**Pull request merged**
