### PR TITLE
New annotation figure

### PR DESCRIPTION
**Pull request by yardencsGitHub**
According to minor point 1 this new figure should replace figures 1-3
Figure 2 - the statistics of birdsong - can move to the supplementary materials.

### CODE REVIEW

**Comment by NickleDave** [comment]
@yardencsGitHub does this mean you don't need me to regenerate the old 'fig0'?
I see you added related .eps / .ai files in the fig0 folder in some commit?

**Comment by yardencsGitHub** [comment]
@NickleDave, please create the figure (the old 'fig0') in vector format.
The .eps,.ai are (I believe) older versions. I don't think I created those.
This PR adds a graphics (/doc/article/figures/mainfig_explain_annotation_issues/mainfig_annotation_and_its_issuesmain.ai) containing the existing 'fig0' but as an image and not in vector format.

**Comment by yardencsGitHub** [comment]
I saw that you have a notebook creating this figure.
Actually tried to run it but needed the spectrogram (.npz) file

**Comment by NickleDave** [comment]
My bad, I didn't look closely enough at those figures.

Adding in a branch now.

Will merge into master, then you can rebase this on it and use the files.

**Comment by NickleDave** [comment]
I rebased on master and force pushed.

If you check your local copy out and then do `git pull --rebase` you should have the files you need in the branch.

You can fix up the figure that uses them and push to this branch.

**Comment by NickleDave** [comment]
Hey, just checking -- what's going on with all the "merge branch" commits? I saw there was one on master too?

**Comment by yardencsGitHub** [comment]
Ah. Snag. I'm using GitHub Desktop on my laptop and might have accidentally misunderstood its messages
(We doing 'pull' it asked to 'commit' the merge in my local)

Any problem merging this pull request? #118 ?

**Comment by NickleDave** [comment]
Yes, it's not the end of the world, I'm just extra paranoid and hoping to avoid having to put out any git fires.

Will merge now -- I take it you're done adding to this.

**Comment by NickleDave** [comment]
@yardencsGitHub it's asking you to "merge" because your local history doesn't match after I force push to remote. That's why I asked you to `git pull --rebase` 

> I rebased on master and force pushed.
> 
> If you check your local copy out and then do `git pull --rebase` you should have the files you need in the branch.
> 
> You can fix up the figure that uses them and push to this branch.

You're pulling in the remote changes, and git tries to merge them.
Whenever it suddenly asks you to merge for no reason, **don't** just do it.

That's what causes the repeated commits in history, because you have the local versions, and then you pull in the re-written history commits that are the same thing.

If it asks you to write a merge commit, just remove the text from the file so it aborts because there's no message. That's how I cancel it, and then just say `git merge --abort` and finally `git pull --rebase`

I'm going to rewrite history on master to get rid of the duplicate commits.
**Please** do `git pull --rebase` the next time you `git checkout master`

**Pull request merged**
