### PR TITLE
Update canaries longtrain

### LINKED ISSUE #84: add/update canary config files
@yardencsGitHub can you please make sure the config files for canaries are what you are using for the resubmission?
Please provide all the configuration files someone would need to replicate the learning curves.
We'll also want configs for follow-up experiments but bare minimum should be ability to reproduce learning curves

### PR DESCRIPTION
**Pull request by yardencsGitHub**
This PR closes #84 and #86.
Added config files for train_dur = 6000 for 3 canaries (in /data//configs/Canaries..)
Added results (error_across_birds.csv) to /results/Canaries/long_train.
Added a script  src/scripts/make_error_eval_with_and_without_output_transforms.py to calculate error metric from EVAL configs.

Important TODO (@NickleDave, please see if this is an easy fix or a principled issue): it is not possible to include a 'normalize_spectrograms = True/False' in the [EVAL] part of .toml files. 
This was not a problem for the canary data where all spectrograms exist but needs to be fixed.

### CODE REVIEW

**Comment by NickleDave** [comment]
Hi @yardencsGitHub just checking to make sure I understand

> Important TODO (@NickleDave, please see if this is an easy fix or a principled issue): it is not possible to include a 'normalize_spectrograms = True/False' in the [EVAL] part of .toml files.
> This was not a problem for the canary data where all spectrograms exist but needs to be fixed.

You're right that there's no option named 'normalize_spectrograms' ... but if you need to do this for `predict` or `eval` you specify a value for `spect_scaler_path` like in this config:
https://github.com/yardencsGitHub/tweetynet/blob/2a175392c4384e9e41d67f3bda471ea17c292c8d/data/configs/Bengalese_Finches/BFSongRepository/bl26lb16/041912/bl26lb16_eval_041912.toml
Is that what you're asking about?

I realize now that you bring this up it's not super obvious, but the functionality is there.

**Comment by yardencsGitHub** [comment]
Thanks @NickleDave. Now I get it.
Let me know if ok to merge (or just do it)

**Comment by NickleDave** [comment]
Before you merge this in...

We should avoid repeating ourselves wherever possible, to minimize the possibility that some discrepancy results from a cut-and-paste error, or, more likely, because we change/fix something in one place but fail to do so for the copy.

That includes the eval script you added which is basically a cut-and-paste of huge chunks of the `make_error` script.

I would prefer to take the common functionality and put it into the `article` package, then have exactly one 'learncurve' and one 'eval' with and without transforms script.

(We should also just take the `gardner` package--which is really just the `SongAnnotationGUI` annotation module--and put it into the `article` package. We can change this without it affecting anything, because of how that annotation format gets installed.)

I also need to write an eval script anyway, because I plan to 'eval' the best BFSongRepo learncurve models on the other days from the dataset.

So how about I do that and then you re-run these results to make sure the script that I write works for you as well?

I could talk later this afternoon if what I'm saying here is not clear.

**Comment by yardencsGitHub** [comment]
That's fine.
I added the script b.c. I needed it to get results.
For a reason that is not clear to me evaluating the metrics is very very slow.
I takes o(1 day) just to evaluate metrics for a single learncurve experiment.
So re-running right now is out of the question imo

**Comment by NickleDave** [comment]
yes, totally understand needing to get results. 
My fault for not co-ordinating better with you so we could do things right the first time.

We should re-run later to make sure we get the same answer.
I need to focus on bf results + hvc today and tomorrow but will include rewriting eval scripts in that.
Let's sync soon after I make progress.

**Comment by NickleDave** [comment]
I'm just going to go ahead and merge, and then raise an issue to re-run once we have final versions of code, so I can go ahead with other clean-ups + re-factoring and not worry about those changes conflicting with this

**Pull request merged**
