### PR TITLE
Visualize net output

### PR DESCRIPTION
**Pull request by NickleDave**
this PR captures the commits from #111 (as far I can tell) **without** the repeated commits that somehow got added multiple times from the article-revisions branch

### CODE REVIEW

**Comment by NickleDave** [comment]
@yardencsGitHub please examine these files and confirm it captures what you want to add before I squash and merge the commits

**Comment by NickleDave** [comment]
Once you have confirmed I will also close (not merge!) #111 to avoid borking the commit history

**Comment by NickleDave** [comment]
Also please 🙏 stop doing whatever you are doing with .gitignore in vscode that causes that file to get secretly added to random commits, because this is extra painful to fix

whatever you're trying to do, let me know and I can help you find some other way to do it

**Comment by yardencsGitHub** [comment]
This runs well. Can merge.
I'll stop messing with .gitignore

**Comment by NickleDave** [comment]
Excellent, thank you

**Pull request merged**
