### PR TITLE
Used VocalDataset in canary metrics

### PR DESCRIPTION
**Pull request by yardencsGitHub**
updates in src/scripts/Canaries/eval_without_and_with_output_transforms.py implement the new VocalDataset.
Additional changes to files required:
1. use of alphanumeric mapping of integer syllable tags - This avoids issues with double-digit integers in calculating segment error rates.
e.g.
y_pred_labels = ''.join([Alphanumeric[int(x)] for x in y_pred_labels])
with
Alphanumeric = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'

2. Loading and providing the time vector 't' to labelfuncs.lbl_tb2segments via
t_vec = cpio.loadmat(str(spect_path[0]),struct_as_record=False, squeeze_me=True)['t']

### CODE REVIEW

**Comment by NickleDave** [comment]
Hey @yardencsGitHub this looks good, thank you for fixing.
I requested a couple of minor changes--I'm sure it works fine as-is, just want to make sure the code is super explicit, mainly for our own sanity a month from now :)

**Comment by NickleDave** [comment]
Also can you just `git commit --amend` to change `Voval` to `Vocal` please?

You can make the changes with another commit and then use interactive rebase to merge it into the previous one as a "fixup"
https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history

And I pushed some more commits after you started this PR I think, so you'll need to do
```terminal
git checkout master
git pull --rebase  # just in case I made any dumb force pushes that rewrote history -- not sure 😬 
git checkout Implement-VocalDataset-for-evaluating-canary-data
git rebase master
```

**Comment by yardencsGitHub** [comment]
@NickleDave , Please merge PR #237 in vak. 
This is the cause for your third point about the 'labelfuncs'

**Comment by NickleDave** [comment]
whoops sorry!
Just merged in

**Comment by NickleDave** [comment]
@yardencsGitHub just letting you know some of the fixes I made in #49 apply to your script here -- e.g. that `import vak.labels as labelfuncs` and the calls to `lbl_tb2segments` that now require the timebins vector `t`

**Comment by yardencsGitHub** [comment]
@NickleDave , 
Got it .
Thanks!

**Comment by NickleDave** [comment]
@yardencsGitHub just checking back -- were you able to make these changes?

**Comment by yardencsGitHub** [comment]
I think so. 
But, I probably need to push another commit and rebase master

**Pull request merged**
